# Generated by Django 4.0.4 on 2022-07-24 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_relative_delete_family'),
    ]
    operations = [
        migrations.AddField(
            model_name='relative',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
