# Generated by Django 4.0.6 on 2022-07-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_relative_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='born',
            field=models.DateField(max_length=50),
        ),
    ]
