# Generated by Django 4.0.6 on 2022-07-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_relative_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='born',
        ),
    ]
